name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore
      run: dotnet restore AutomationTesting/AutomationTesting.sln

    - name: Clean
      run: dotnet clean AutomationTesting/AutomationTesting.sln --configuration Release

    - name: Build
      run: dotnet build AutomationTesting/AutomationTesting.sln --configuration Release --no-restore
